/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        display: ["Manrope", "ui-sans-serif", "system-ui", "sans-serif"],
        sans: ["Manrope", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["\"JetBrains Mono\"", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      colors: {
        ink: { DEFAULT: "#0A0D19", 2: "#0E1222" },
        surface: { DEFAULT: "#11162A", 2: "#171D35" },
        panel: { DEFAULT: "#151B31", 2: "#1B2240" },
        raised: "#232B4D",
        line: { DEFAULT: "#2B3457", 2: "#212948" },
        txt: { DEFAULT: "#F2F4FF", 2: "#C3C9E6" },
        dim: { DEFAULT: "#8B93B8", 2: "#646C92" },
        brand: { DEFAULT: "#6E5BFF", 2: "#8B7CFF", 3: "#5546E0", fg: "#FFFFFF" },
        gold: { DEFAULT: "#F5C451", 2: "#FFD97A", fg: "#2A1F05" },
        aqua: { DEFAULT: "#5CE1E6", 2: "#8FF0F3", fg: "#06201F" },
        win: { DEFAULT: "#3DDC97", 2: "#7CF0BF" },
        danger: { DEFAULT: "#FF5470", 2: "#FF8AA0" },
        warn: "#FFB020",
        info: "#6AA8FF",
        // legacy token remap (used by Roulette / Blackjack / Sweet Bonanza engines)
        night: {
          bg: "#0A0D19",
          surface: "#11162A",
          card: "#151B31",
          cardhover: "#1B2240",
          elevated: "#232B4D",
          border: "#2B3457",
          bordersub: "#212948",
          sidebar: "#171D35",
          chat: "#11162A",
        },
        mint: { DEFAULT: "#6E5BFF", hover: "#8B7CFF" },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
      },
      boxShadow: {
        card: "0 18px 40px rgba(0,0,0,0.45)",
        raised: "0 22px 60px rgba(0,0,0,0.55)",
        "glow-brand": "0 0 0 1px rgba(110,91,255,0.28), 0 0 32px rgba(110,91,255,0.28)",
        "glow-gold": "0 0 0 1px rgba(245,196,81,0.22), 0 0 28px rgba(245,196,81,0.18)",
        "glow-aqua": "0 0 0 1px rgba(92,225,230,0.22), 0 0 28px rgba(92,225,230,0.16)",
        "glow-win": "0 0 0 1px rgba(61,220,151,0.25), 0 0 34px rgba(61,220,151,0.2)",
        "glow-danger": "0 0 0 1px rgba(255,84,112,0.25), 0 0 34px rgba(255,84,112,0.2)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
