import { Rocket, Dices, Bomb, Coins, Disc3, Spade, Candy, Target, Infinity, Castle, LoaderPinwheel, Egg } from "lucide-react";

export const GAMES = [
  {
    id: "crash",
    name: "Crash",
    route: "/crash",
    icon: Rocket,
    color: "#3DDC97",
    group: "Originals",
    tag: "Beliebt",
    tagline: "Rakete steigt, Multiplikator wächst — steig aus, bevor sie abstürzt.",
    edge: "1 % Hausvorteil",
    maxWin: "bis 100x",
  },
  {
    id: "dice",
    name: "Dice",
    route: "/dice",
    icon: Dices,
    color: "#6AA8FF",
    group: "Originals",
    tag: "Neu",
    tagline: "Ziel setzen, Über oder Unter wählen, würfeln — bis 49,5x.",
    edge: "1 % Hausvorteil",
    maxWin: "bis 49,5x",
  },
  {
    id: "mines",
    name: "Mines",
    route: "/mines",
    icon: Bomb,
    color: "#5CE1E6",
    group: "Originals",
    tag: "Neu",
    tagline: "25 Felder, versteckte Minen. Jeder Edelstein erhöht den Multiplikator.",
    edge: "1 % Hausvorteil",
    maxWin: "bis 2.400x",
  },
  {
    id: "coinflip",
    name: "Coinflip",
    route: "/coinflip",
    icon: Coins,
    color: "#F5C451",
    group: "Originals",
    tag: "Neu",
    tagline: "Kopf oder Zahl. Gewinne, verdopple weiter oder nimm den Pot mit.",
    edge: "2 % Hausvorteil",
    maxWin: "1,96x pro Flip",
  },
  {
    id: "plinko",
    name: "Plinko",
    route: "/plinko",
    icon: Target,
    color: "#FF8A5B",
    group: "Originals",
    tag: "Neu",
    tagline: "Kugel fallen lassen, durch die Pins hüpfen — die Außenfächer zahlen bis 1.000x.",
    edge: "1 % Hausvorteil",
    maxWin: "bis 1.000x",
  },
  {
    id: "limbo",
    name: "Limbo",
    route: "/limbo",
    icon: Infinity,
    color: "#C084FC",
    group: "Originals",
    tag: "Neu",
    tagline: "Wähle dein Ziel-Multiplikator. Liegt das Ergebnis darüber, gewinnst du.",
    edge: "1 % Hausvorteil",
    maxWin: "bis 1.000.000x",
  },
  {
    id: "tower",
    name: "Tower",
    route: "/tower",
    icon: Castle,
    color: "#FBBF24",
    group: "Originals",
    tag: "Neu",
    tagline: "Stufe für Stufe nach oben. Jede Etage erhöht den Multiplikator — Fallen beenden den Aufstieg.",
    edge: "1 % Hausvorteil",
    maxWin: "bis 6.400x",
  },
  {
    id: "wheel",
    name: "Wheel",
    route: "/wheel",
    icon: LoaderPinwheel,
    color: "#38BDF8",
    group: "Originals",
    tag: "Neu",
    tagline: "Glücksrad mit drei Risikostufen — vom sicheren 1,2x bis zum 11,8x-Jackpot.",
    edge: "~2 % Hausvorteil",
    maxWin: "bis 11,8x",
  },
  {
    id: "chicken-road",
    name: "Chicken Road",
    route: "/chicken-road",
    icon: Egg,
    color: "#FDE68A",
    group: "Originals",
    tag: "Neu",
    tagline: "Bring das Huhn über die Straße. Jede Spur erhöht den Multiplikator — Autos beenden den Lauf.",
    edge: "2 % Hausvorteil",
    maxWin: "bis 25x",
  },
  {
    id: "roulette",
    name: "Roulette",
    route: "/roulette",
    icon: Disc3,
    color: "#FF5470",
    group: "Klassiker",
    tag: "Klassiker",
    tagline: "Europäisches Roulette: Chips setzen, Zahlen, Dutzende, Rot/Schwarz — bis 36x.",
    edge: "2,7 % Hausvorteil",
    maxWin: "bis 36x",
  },
  {
    id: "blackjack",
    name: "Blackjack",
    route: "/blackjack",
    icon: Spade,
    color: "#8FF0F3",
    group: "Klassiker",
    tag: "Klassiker",
    tagline: "Schlage den Dealer. Split, Double und Blackjack 3:2.",
    edge: "~0,5 % Hausvorteil",
    maxWin: "3:2",
  },
  {
    id: "sweet-bonanza",
    name: "Sweet Bonanza",
    route: "/sweet-bonanza",
    icon: Candy,
    color: "#F472B6",
    group: "Klassiker",
    tag: "Slot",
    tagline: "Candy-Slot mit Tumble-Mechanik, Freispielen und Multi-Gläsern.",
    edge: "~3,5 % Hausvorteil",
    maxWin: "bis 21.100x",
  },
];

export const GAME_BY_NAME = Object.fromEntries(GAMES.map((g) => [g.name, g]));
export const GAME_BY_ROUTE = Object.fromEntries(GAMES.map((g) => [g.route, g]));
export const gameColor = (name) => GAME_BY_NAME[name]?.color || "#8B93B8";
